version: '3.7'
services:
  code2seq-paths-php:
    build:
      context: .
    image: "morria/code2seq-paths-php:latest"
    container_name: "code2seq-paths-php"
    volumes:
      - "..:/workspace:cached"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
